[Interface]
Address = 10.3.0.1/24
ListenPort = 51820
PrivateKey = +AQ7gYb+X6iuw5tMcBnM6X17lomOkxkObXfe/M+btE8=
PostUp = iptables -A INPUT -p udp --dport 51820 -j ACCEPT || true; iptables -A FORWARD -i warp -o wg0 -j ACCEPT || true; iptables -A FORWARD -i wg0 -j ACCEPT || true; iptables -t nat -A POSTROUTING -o warp -j MASQUERADE || true; ip route add default dev warp table 110 || true; ip rule add iif wg0 table 110 || true;
PostDown = iptables -D INPUT -p udp --dport 51820 -j ACCEPT || true; iptables -D FORWARD -i warp -o wg0 -j ACCEPT || true; iptables -D FORWARD -i wg0 -j ACCEPT || true; iptables -t nat -D POSTROUTING -o warp -j MASQUERADE || true; ip route del default dev warp table 110 || true; ip rule del iif wg0 table 110 || true;

[Peer]
# Кембридж 1.1
PublicKey = DlwW7O6WTvzVVhZS+M37XN5Pkzis63VhcareKDhGJhA=
AllowedIPs = 10.3.0.2/32

[Peer]
# Кембридж 900.1
PublicKey = 9N6pyDMBYf/5EdkCq3Z4AY2qK1wVYH1GWVHi9qKKlkE=
AllowedIPs = 10.3.0.3/32

[Peer]
# Keenetic Start
PublicKey = CXqqboriIPIdCgUFVUkLgJU7kX8gXs7buQnMIoHt7BM=
AllowedIPs = 10.3.0.4/32
